bump_version: null
lint: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Simone Carpanzano, Francesco Lescai
  description: A pipeline to investigate horizontal gene transfer from NGS data
  force: false
  is_nfcore: true
  name: hgtseq
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.1.0
update: null
