contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #hgtseq channel"
    url: https://nfcore.slack.com/channels/hgtseq
    about: Discussion about the nf-core/hgtseq pipeline
