# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-biovizbase=1.58.0
  - bioconda::bioconductor-genomeinfodb=1.46.2
  - bioconda::bioconductor-genomicranges=1.62.1
  - bioconda::bioconductor-ggbio=1.58.0
  - conda-forge::r-base=4.5.3
  - conda-forge::r-rmarkdown=2.32
  - conda-forge::r-tidyverse=2.0.0
